export const articleData = [
  {
    title: 'Custom Solutions',
    created: '04/08/2020',
    lastUpdated: '24/03/2021',
    icon: '/images/icons/white/BESPOKE.png',
    disabled: false,
    key: 0,
  },
  {
    title: 'Zendesk Products',
    created: '01/07/2020',
    lastUpdated: '27/02/2021',
    icon: '/images/icons/white/SCOPE.png',
    disabled: false,
    key: 1,
  },
  {
    title: '1 to 1 Support',
    created: '04/08/2020',
    lastUpdated: '24/03/2021',
    icon: '/images/icons/white/CRM.png',
    disabled: true,
    key: 2,
  },
  {
    title: 'Client Training',
    created: '04/08/2020',
    lastUpdated: '24/03/2021',
    icon: '/images/icons/white/JOURNEY.png',
    disabled: true,
    key: 3,
  },
  {
    title: 'Development',
    created: '04/08/2020',
    lastUpdated: '24/03/2021',
    icon: '/images/icons/white/TOOLBOX.png',
    disabled: true,
    key: 4,
  },
  {
    title: 'Privacy Policy',
    created: '04/08/2020',
    lastUpdated: '24/03/2021',
    icon: '/images/icons/white/ONBOARD.png',
    disabled: true,
    key: 5,
  },
];
